//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeerTicket.API.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class API_UploadStatus
    {
        public int Upload_Id { get; set; }
        public string Upload_Status { get; set; }
        public string Upload_Detail { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    }
}
