//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Issuance.API.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CardInfo
    {
        public int Id { get; set; }
        public Nullable<int> Token_Id { get; set; }
        public string card_number { get; set; }
        public Nullable<int> cvv { get; set; }
        public string card_holder { get; set; }
        public Nullable<int> expire_year { get; set; }
        public Nullable<int> expire_date { get; set; }
        public Nullable<int> postal { get; set; }
        public string phone { get; set; }
    }
}
