//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Issuance.API.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CouponProductType
    {
        public int Id { get; set; }
        public string ProductCode { get; set; }
        public string ProductType { get; set; }
        public string dbUser { get; set; }
        public string dbPwd { get; set; }
        public string dbName { get; set; }
        public string dbTable { get; set; }
        public string dbProductCode { get; set; }
        public string dbProductName { get; set; }
        public string dbCountryCode { get; set; }
        public string dbStatusCode { get; set; }
        public string dbStatusValue { get; set; }
        public Nullable<short> Status { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string dbHotelName { get; set; }
        public string dbHotelChain { get; set; }
        public string dbFlightNumber { get; set; }
        public string dbAirlineName { get; set; }
        public string dbAirportCode { get; set; }
    }
}
