//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Issuance.API.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CouponGeneration
    {
        public int Id { get; set; }
        public Nullable<int> Generation_Id { get; set; }
        public Nullable<int> Campaign_Id { get; set; }
        public string Email { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<short> Status { get; set; }
        public Nullable<byte> Distribution { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Distributed { get; set; }
        public Nullable<System.DateTime> Approved { get; set; }
        public string VoucherId { get; set; }
        public string FlightNumber { get; set; }
        public string DateOfFlight { get; set; }
        public string Gateway { get; set; }
    }
}
