//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Issuance.API.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class creditcard_request
    {
        public string token_id { get; set; }
        public Nullable<System.DateTime> pre_timestamp { get; set; }
        public Nullable<System.DateTime> void_timestamp { get; set; }
        public Nullable<System.DateTime> force_timestamp { get; set; }
        public string fullname { get; set; }
        public string card_number { get; set; }
        public Nullable<short> cvv { get; set; }
        public Nullable<int> expireYY { get; set; }
        public Nullable<int> expireMM { get; set; }
        public string address { get; set; }
        public string address2 { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string postal { get; set; }
        public string phone { get; set; }
        public string card_token { get; set; }
        public Nullable<bool> preauth { get; set; }
        public string pre_card_type { get; set; }
        public Nullable<decimal> pre_card_amount { get; set; }
        public Nullable<int> pre_card_expireYY { get; set; }
        public Nullable<int> pre_card_expireMM { get; set; }
        public string pre_auth_code { get; set; }
        public string pre_cvv_check { get; set; }
        public string pre_avs_check { get; set; }
        public Nullable<bool> forceclose { get; set; }
        public string force_card_type { get; set; }
        public Nullable<decimal> force_card_amount { get; set; }
        public Nullable<int> force_card_expireYY { get; set; }
        public Nullable<int> force_card_expireMM { get; set; }
        public string force_auth_code { get; set; }
        public string force_cvv_check { get; set; }
        public string force_avs_check { get; set; }
        public int Id { get; set; }
        public Nullable<decimal> Amount { get; set; }
    }
}
