//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Issuance.API.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class crm_pages
    {
        public int id { get; set; }
        public string title_en { get; set; }
        public string title_fr { get; set; }
        public string title_es { get; set; }
        public string content_en { get; set; }
        public string content_fr { get; set; }
        public string content_es { get; set; }
        public Nullable<short> status { get; set; }
    }
}
