//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Issuance.API.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class invoice_request
    {
        public string token_id { get; set; }
        public string fullname { get; set; }
        public string Number { get; set; }
        public int Id { get; set; }
        public Nullable<decimal> Amount { get; set; }
    }
}
