//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeerTicket.API.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class log
    {
        public Nullable<System.DateTime> timestamp { get; set; }
        public string request_type { get; set; }
        public string request_details { get; set; }
        public Nullable<int> token_id { get; set; }
        public string action { get; set; }
        public int Id { get; set; }
    }
}
