//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeerTicket.API.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class portal_functions
    {
        public int id { get; set; }
        public Nullable<int> module_id { get; set; }
        public string title { get; set; }
        public string icon { get; set; }
        public string target { get; set; }
    }
}
