//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeerTicket.API.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class portal_role_function_access
    {
        public int id { get; set; }
        public Nullable<int> role_id { get; set; }
        public Nullable<int> function_id { get; set; }
        public Nullable<int> func_add { get; set; }
        public Nullable<int> func_edit { get; set; }
        public Nullable<int> func_delete { get; set; }
        public Nullable<int> func_active_deactive { get; set; }
    }
}
