//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeerTicket.API.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class token_request
    {
        public string token_id { get; set; }
        public Nullable<System.DateTime> token_timestamp { get; set; }
        public string transaction_id { get; set; }
        public string transaction_type { get; set; }
        public Nullable<decimal> transaction_total { get; set; }
        public Nullable<decimal> transaction_taxes { get; set; }
        public Nullable<bool> taxes_included { get; set; }
        public string device_cookie { get; set; }
        public string device_indicator { get; set; }
        public string device_address { get; set; }
        public string business_type { get; set; }
        public int Id { get; set; }
        public string booking_number { get; set; }
        public Nullable<System.DateTime> depart_date { get; set; }
        public Nullable<System.DateTime> return_date { get; set; }
        public string brand_id { get; set; }
        public string product_codes { get; set; }
    }
}
