//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Issuance.API.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class transaction_car
    {
        public string token_id { get; set; }
        public Nullable<System.DateTime> create_timestamp { get; set; }
        public string rental_company { get; set; }
        public string pickup_location { get; set; }
        public Nullable<System.DateTime> pickup_datetime { get; set; }
        public string pickup_address { get; set; }
        public string pickup_phone { get; set; }
        public string pickup_state { get; set; }
        public string pickup_postal { get; set; }
        public string pickup_country { get; set; }
        public string return_location { get; set; }
        public Nullable<System.DateTime> return_datetime { get; set; }
        public string return_address { get; set; }
        public string return_phone { get; set; }
        public string return_state { get; set; }
        public string return_postal { get; set; }
        public string return_country { get; set; }
        public Nullable<decimal> rental_total { get; set; }
        public Nullable<decimal> rental_tax { get; set; }
        public int Id { get; set; }
    }
}
