//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeerTicket.API.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class transaction_cruise
    {
        public string token_id { get; set; }
        public Nullable<System.DateTime> create_timestamp { get; set; }
        public string cruise_name { get; set; }
        public string cruise_poc_resort { get; set; }
        public Nullable<int> cruise_duration { get; set; }
        public Nullable<decimal> cruise_amount { get; set; }
        public Nullable<decimal> cruise_tax { get; set; }
        public Nullable<System.DateTime> cruise_datetime { get; set; }
        public int Id { get; set; }
    }
}
