//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Issuance.API.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction_Update
    {
        public string token { get; set; }
        public Nullable<System.DateTime> create_timestamp { get; set; }
        public string agency_code { get; set; }
        public string agency_name { get; set; }
        public string agency_address { get; set; }
        public string agency_address2 { get; set; }
        public string agency_postal { get; set; }
        public string agency_city { get; set; }
        public string agency_state { get; set; }
        public string agency_country { get; set; }
        public string agency_email { get; set; }
        public string agency_consortium { get; set; }
        public string agency_type { get; set; }
        public string wings_campaign { get; set; }
        public string wings_email { get; set; }
        public string wings_first { get; set; }
        public string wings_middle { get; set; }
        public string wings_last { get; set; }
        public string wings_address { get; set; }
        public string wings_address2 { get; set; }
        public string wings_city { get; set; }
        public string wings_region { get; set; }
        public string wings_country { get; set; }
        public string wings_postal { get; set; }
        public string rental_company { get; set; }
        public string pickup_location { get; set; }
        public Nullable<System.DateTime> pickup_datetime { get; set; }
        public string pickup_address { get; set; }
        public string pickup_phone { get; set; }
        public string pickup_state { get; set; }
        public string pickup_postal { get; set; }
        public string pickup_country { get; set; }
        public string return_location { get; set; }
        public Nullable<System.DateTime> return_datetime { get; set; }
        public string return_address { get; set; }
        public string return_phone { get; set; }
        public string return_state { get; set; }
        public string return_postal { get; set; }
        public string return_country { get; set; }
        public Nullable<decimal> rental_total { get; set; }
        public Nullable<decimal> rental_tax { get; set; }
        public string cruise_name { get; set; }
        public string cruise_poc_resort { get; set; }
        public string cruise_duration { get; set; }
        public Nullable<decimal> cruise_amount { get; set; }
        public Nullable<decimal> cruise_tax { get; set; }
        public Nullable<System.DateTime> cruise_datetime { get; set; }
        public string excursion_name { get; set; }
        public string excursion_supplier { get; set; }
        public string excursion_location { get; set; }
        public Nullable<System.DateTime> excursion_datetime { get; set; }
        public Nullable<decimal> excursion_amount { get; set; }
        public Nullable<decimal> excursion_tax { get; set; }
        public string hotel_provider { get; set; }
        public string hotel_name { get; set; }
        public string hotel_address { get; set; }
        public string hotel_phone { get; set; }
        public string hotel_city { get; set; }
        public string hotel_state { get; set; }
        public string hotel_postal { get; set; }
        public string hotel_latitude { get; set; }
        public string hotel_longitude { get; set; }
        public string hotel_country { get; set; }
        public Nullable<System.DateTime> hotel_checkin_datetime { get; set; }
        public Nullable<System.DateTime> hotel_checkout_datetime { get; set; }
        public Nullable<decimal> hotel_total { get; set; }
        public Nullable<decimal> hotel_tax { get; set; }
        public string inairline_name { get; set; }
        public string inflight_number { get; set; }
        public Nullable<System.DateTime> indeparture_datetime { get; set; }
        public string indeparture_city { get; set; }
        public string indeparture_airport { get; set; }
        public Nullable<System.DateTime> inarrival_datetime { get; set; }
        public string inarrival_city { get; set; }
        public string inarrival_airport { get; set; }
        public string outairline_name { get; set; }
        public string outflight_number { get; set; }
        public Nullable<System.DateTime> outdeparture_datetime { get; set; }
        public string outdeparture_city { get; set; }
        public string outdeparture_airport { get; set; }
        public Nullable<System.DateTime> outarrival_datetime { get; set; }
        public string outarrival_city { get; set; }
        public string outarrival_airport { get; set; }
        public string ticket_number { get; set; }
        public string ticket_class { get; set; }
        public Nullable<decimal> total_amount { get; set; }
        public string passenger_dob { get; set; }
        public string passenger_title { get; set; }
        public string passenger_first { get; set; }
        public string passenger_middle { get; set; }
        public string passenger_last { get; set; }
        public string passenger_email { get; set; }
        public string passenger_phone { get; set; }
        public string passenger_loyalty { get; set; }
        public string pnr_number { get; set; }
        public Nullable<decimal> pnr_total { get; set; }
        public Nullable<decimal> pnr_extra_fees { get; set; }
        public string pnr_trip_type { get; set; }
        public Nullable<bool> pnr_group_flag { get; set; }
        public string shipping_first { get; set; }
        public string shipping_middle { get; set; }
        public string shipping_last { get; set; }
        public string shipping_email { get; set; }
        public string shipping_address { get; set; }
        public string shipping_address2 { get; set; }
        public string shipping_city { get; set; }
        public string shipping_state { get; set; }
        public string shipping_postal { get; set; }
        public string shipping_country { get; set; }
        public string shipping_phone { get; set; }
        public int Id { get; set; }
        public string incall { get; set; }
        public Nullable<System.DateTime> update_timestamp { get; set; }
    }
}
