//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeerTicket.API.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class transaction_error_log
    {
        public int Id { get; set; }
        public string error_num { get; set; }
        public string error_text_en { get; set; }
        public string error_text_fr { get; set; }
        public string error_text_sp { get; set; }
    }
}
