//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Issuance.API.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class transaction_agent
    {
        public string token_id { get; set; }
        public Nullable<System.DateTime> create_timestamp { get; set; }
        public string wings_campaign { get; set; }
        public string wings_email { get; set; }
        public string wings_first { get; set; }
        public string wings_middle { get; set; }
        public string wings_last { get; set; }
        public string wings_address { get; set; }
        public string wings_address2 { get; set; }
        public string wings_city { get; set; }
        public string wings_region { get; set; }
        public string wings_country { get; set; }
        public string wings_postal { get; set; }
        public int Id { get; set; }
    }
}
