//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeerTicket.API.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class transaction_shipping
    {
        public string token_id { get; set; }
        public Nullable<System.DateTime> create_timestamp { get; set; }
        public string shipping_first { get; set; }
        public string shipping_middle { get; set; }
        public string shipping_last { get; set; }
        public string shipping_email { get; set; }
        public string shipping_address { get; set; }
        public string shipping_address2 { get; set; }
        public string shipping_city { get; set; }
        public string shipping_state { get; set; }
        public string shipping_postal { get; set; }
        public string shipping_country { get; set; }
        public string shipping_phone { get; set; }
        public int Id { get; set; }
    }
}
