//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeerTicket.API.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VoucherCampaign
    {
        public int Id { get; set; }
        public Nullable<int> TypeId { get; set; }
        public Nullable<int> FundingId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> BrandId { get; set; }
        public string CampaignName { get; set; }
        public string incProduct { get; set; }
        public string exclProduct { get; set; }
        public Nullable<decimal> value { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public byte[] Updated { get; set; }
        public string htmlEnglish { get; set; }
        public string htmlFrench { get; set; }
        public string urlEnglish { get; set; }
        public string urlFrench { get; set; }
        public string token { get; set; }
        public Nullable<System.DateTime> DepartDate { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
    
        public virtual CouponBrand CouponBrand { get; set; }
        public virtual CouponCategory CouponCategory { get; set; }
        public virtual CouponFunding CouponFunding { get; set; }
        public virtual CouponType CouponType { get; set; }
    }
}
