//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeerTicket.API.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VoucherGeneration
    {
        public int Id { get; set; }
        public Nullable<int> CampaignId { get; set; }
        public Nullable<byte> Distribution { get; set; }
        public Nullable<int> Coupons { get; set; }
        public Nullable<short> Status { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Approved { get; set; }
        public Nullable<System.DateTime> Distributed { get; set; }
        public string Upload_Status { get; set; }
        public string Upload_Detail { get; set; }
        public string FlightNumber { get; set; }
        public Nullable<int> Amount { get; set; }
        public string DepartureDate { get; set; }
    }
}
